- name: Create directory "wmlite"
  file:
    path: "{{ wmlite_directory }}"
    state: directory
    recurse: yes 

- name: Download WebMail Lite 
  get_url: 
    url: "{{ download_url }}"
    dest: "{{ download_path }}"

- name: Unpacking the archive created earlier directory
  ansible.builtin.unarchive:
    src: "{{ download_path }}/webmail_php.zip"
    dest: "{{ wmlite_directory }}"
    remote_src: yes

- name: Setting the owner
  file: 
    path: "{{ wmlite_directory }}"
    state: directory
    recurse: yes 
    owner: apache
    group: apache

- name: Configure NGINX 
  template: 
    src: webmail_lite.conf.j2
    dest: "{{ webmail_lite_conf }}"

- name: Restarted NGINX  
  service: 
    name: nginx 
    state: restarted

- name: Create DataBase webmail
  community.mysql.mysql_db:
    name: "{{ name_db }}"
    encoding: utf8
    collation: utf8_bin
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Create User webmail
  community.mysql.mysql_user:
    name: "{{ user_db }}"
    password: "{{ pass_user_db }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"