---
- name: System preparation
  include_tasks: preparation_system.yaml

- name: Install Web-Server
  include_tasks: deploy_websever.yaml

- name: Install MariaDB
  include_tasks: deploy_mariadb.yaml

- name: Install WebMail Lite
  include_tasks: install_webmail.yaml

- debug:
    msg:
      - "open the browser 'http://{{ ansible_ssh_host }}/?install' "